import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm';
const SUPABASE_URL="https://ekkaagqovdmcdexrjosh.supabase.co",SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVra2FhZ3FvdmRtY2RleHJqb3NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4NjU2NTEsImV4cCI6MjA3NTQ0MTY1MX0.mmVl7C0Hkzrjoks7snvHWMYk-ksSXkUWzVexhtkozRA";
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
let isAdmin=!1;
const DOM={container:document.getElementById("newsBannersContainer"),adminPanel:document.getElementById("newsAdminPanel"),toggleBtn:document.getElementById("toggleNewsAdminBtn"),formSection:document.getElementById("bannerCreationSection"),titleInput:document.getElementById("bannerTitle"),contentInput:document.getElementById("bannerContent"),exitBtn:document.getElementById("exitAdminBtn")};
const COLORS=["#2ecc71","#3498db","#9b59b6","#34495e","#f1c40f","#e67e22","#e74c3c","#1abc9c","#f39c12","#95a5a6"],getRandomColor=()=>COLORS[Math.floor(Math.random()*COLORS.length)],linkify=e=>e.replace(/(\b(https?:\/\/[^\s]+|www\.[^\s]+)\b)/g,e=>`<a href="${e.startsWith("http")?e:"http://"+e}" target="_blank" rel="noopener">${e}</a>`).replace(/\n/g,"<br>"),formatDate=e=>new Date(e).toLocaleString("es-ES",{dateStyle:"long",timeStyle:"short"});
function createCommentHtml(e,t){const n="true"===localStorage.getItem(`like_${e.id}`);return`<div class="comment-item" data-id="${e.id}"><strong>${e.commenter_name}</strong> <small>(${new Date(e.created_at).toLocaleDateString()})</small>: ${e.comment_text}<div style="text-align:right;margin-top:3px"><button class="like-btn ${n?"liked":""}" data-cid="${e.id}" data-bid="${t}">❤️ ${e.likes||0}</button></div></div>`}
function createBannerHtml(e){const t=e.comments?e.comments.sort((e,t)=>new Date(e.created_at)-new Date(t.created_at)):[],n=t.map(t=>createCommentHtml(t,e.id)).join(""),o=t.length>0?createCommentHtml(t[0],e.id):"";let a=t.length>1?`Ver ${t.length-1} comentarios más...`:1===t.length?"1 comentario":"Sé el primero en comentar";t.length>1&&(a=`<button class="view-comments-btn" data-bid="${e.id}" data-expanded="false">${a}</button>`);const s=`<button class="delete-banner-btn" style="display:${isAdmin?"block":"none"};" data-id="${e.id}">×</button>`;return`<article class="news-banner" style="background-color:${e.color}" data-id="${e.id}">${s}<h2 class="banner-title">${e.title}</h2><p class="banner-date">Publicado: ${formatDate(e.created_at)}</p><div class="banner-text">${linkify(e.content)}</div><div class="banner-footer"><div class="comment-controls">${a}</div><div id="list-${e.id}" class="comments-list">${n}</div><div class="first-comment-wrap">${o}</div><div class="comment-form"><input type="text" placeholder="Tu Nombre" class="c-name" maxlength="30"><textarea placeholder="Comentario..." class="c-text" maxlength="250"></textarea><button class="pub-btn" data-bid="${e.id}">Comentar</button></div></div></article>`}
async function loadBanners(){DOM.container.innerHTML='<p style="text-align:center;margin:30px;color:#888">Cargando noticias...</p>';try{const{data:e,error:t}=await supabase.from("news_banners").select("*, comments:banner_comments(*)").order("created_at",{ascending:!1});if(t)throw t;DOM.container.innerHTML=e.length?e.map(createBannerHtml).join(""):'<p style="text-align:center;margin:30px">No hay noticias aún.</p>'}catch(e){console.error(e),DOM.container.innerHTML='<p style="text-align:center;color:red">Error de conexión.</p>'}}
function toggleAdmin(e=!1){isAdmin=!e&&!isAdmin,DOM.adminPanel.style.display=isAdmin?"flex":"none",DOM.toggleBtn.style.display=isAdmin?"none":"block",DOM.formSection.style.display="none",document.querySelectorAll(".delete-banner-btn").forEach(e=>e.style.display=isAdmin?"block":"none")}
async function handlePublish(){const e=DOM.titleInput.value.trim(),t=DOM.contentInput.value.trim();if(e.length<5||t.length<10)return alert("Título (5+) y contenido (10+) requeridos.");const{error:n}=await supabase.from("news_banners").insert([{title:e,content:t,color:getRandomColor()}]);n?alert("Error al publicar."):(DOM.titleInput.value="",DOM.contentInput.value="",DOM.formSection.style.display="none",loadBanners(),alert("✅ Publicado."))}
async function handleDelete(e){isAdmin&&confirm("¿Eliminar noticia permanentemente?")&&(await supabase.from("news_banners").delete().eq("id",e)).error?alert("Error al eliminar."):document.querySelector(`article[data-id="${e}"]`).remove()}
async function handleComment(e){const t=e.closest(".comment-form"),n=t.querySelector(".c-name").value.trim(),o=t.querySelector(".c-text").value.trim(),a=e.dataset.bid;if(n.length<2||o.length<2)return alert("Escribe un nombre y comentario válido.");e.disabled=!0;const{error:s}=await supabase.from("banner_comments").insert([{banner_id:a,commenter_name:n,comment_text:o}]);s?alert("Error al comentar."):await loadBanners(),e.disabled=!1}
async function handleLike(e){const t=e.dataset.cid,n=`like_${t}`,o="true"===localStorage.getItem(n),a=parseInt(e.textContent.split(" ")[1])||0,s=o?Math.max(0,a-1):a+1;e.innerHTML=`❤️ ${s}`,e.classList.toggle("liked"),o?localStorage.removeItem(n):localStorage.setItem(n,"true"),await supabase.from("banner_comments").update({likes:s}).eq("id",t)}
function toggleComments(e){const t=document.getElementById(`list-${e.dataset.bid}`),n="true"===e.dataset.expanded;t.classList.toggle("expanded",!n),t.nextElementSibling.style.display=n?"block":"none";const o=t.children.length,a=o>1?o-1:0;e.textContent=n?`Ver ${a} comentarios más...`:"Ocultar comentarios",e.dataset.expanded=!n}
document.addEventListener("DOMContentLoaded",()=>{loadBanners(),DOM.toggleBtn.onclick=()=>toggleAdmin(),DOM.exitBtn&&(DOM.exitBtn.onclick=()=>toggleAdmin(!0)),document.getElementById("addBannerBtn").onclick=()=>DOM.formSection.style.display="block",document.getElementById("cancelBannerBtn").onclick=()=>DOM.formSection.style.display="none",document.getElementById("publishBannerBtn").onclick=handlePublish,DOM.container.onclick=e=>{const t=e.target;t.classList.contains("delete-banner-btn")&&handleDelete(t.dataset.id),t.classList.contains("pub-btn")&&handleComment(t),t.classList.contains("like-btn")&&handleLike(t),t.classList.contains("view-comments-btn")&&toggleComments(t)}});
